### ISSUE TITLE
Make Community Standard Files

### ISSUE THREAD

**Issue by TrappyChastity** [Lat3xKitty/lovense-forza#5]
- Code of conduct
- **Contributing**
- **License**
- Issue Template
- Pull Request Template

see [Here for the list](https://github.com/Lat3xKitty/lovense-forza/community)

**Comment by Lat3xKitty** [comment]
TL;DR I don't see this as a big enough project to EVER need any of this. 😅
As I have said before, 30 minute project which I just shared.

Once it's done, it's done, I don't see much more advancements from this project other than a few tweaks here and there, and maybe an addition of a new way of vibration.

All of these require far more effort to setup than will actually help the outcome for it.
